global:
  smtp_smarthost: 'smtp:25'
  smtp_from: 'email@example.com'

# route:
#   receiver: example-email
#   group_by: [alertname]
# receivers:
#  - name: example-email
#    email_configs:

# See https://github.com/prometheus/alertmanager/pull/2827
# https://prometheus.io/docs/alerting/latest/configuration/#telegram_config

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: "telegram"

receivers:
  - name: 'telegram'
    telegram_configs:
    - api_url: https://api.telegram.org
      bot_token: your-token
      chat_id:  your-chat_id

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']