services:
  node_exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node_exporter
    command: '--path.rootfs=/host'
    restart: unless-stopped
    pid: host    
    volumes:
      - /:/host:ro,rslave
    networks:
      - localprom
