services:
  pgexp-apollo-acquisitions:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: pgexp-apollo-acquisitions
    restart: unless-stopped
    networks:
      - localprom
    ports:
      - 9189:9189
    secrets:
      - apollo-acquisitions_uri
    entrypoint: sh -c "export DATA_SOURCE_NAME=$(cat /run/secrets/apollo-acquisitions_uri) && exec postgres_exporter --web.listen-address=:9189 --exclude-databases=template0,template1,rdsadmin" 
    links:
      - prometheus
  
secrets:
  apollo-acquisitions_uri:
    file: ./../secrets/apollo-acquisitions.conn