services:
  pgexp-apollo-db-ro:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: pgexp-apollo-db-ro
    restart: unless-stopped
    networks:
      - localprom
    ports:
      - 9199:9199
    secrets:
      - apollo-db-ro_uri
    entrypoint: sh -c "export DATA_SOURCE_NAME=$(cat /run/secrets/apollo-db-ro_uri) && exec postgres_exporter --web.listen-address=:9199 --exclude-databases=template0,template1,rdsadmin" 
    links:
      - prometheus
  
secrets:
  apollo-db-ro_uri:
    file: ./../secrets/apollo-db-ro.conn