services:
  pgexp-calakmul-sofipo-prod:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: pgexp-calakmul-sofipo-prod
    restart: unless-stopped
    networks:
      - localprom
    ports:
      - 9191:9191
    secrets:
      - calakmul-sofipo-prod_uri
    entrypoint: sh -c "export DATA_SOURCE_NAME=$(cat /run/secrets/calakmul-sofipo-prod_uri) && exec postgres_exporter --web.listen-address=:9191 --exclude-databases=template0,template1,rdsadmin" 
    links:
      - prometheus
  
secrets:
  calakmul-sofipo-prod_uri:
    file: ./../secrets/calakmul-sofipo-prod.conn