services:
  pgexp-sofom-dap-db-mgt-ro:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: pgexp-sofom-dap-db-mgt-ro
    restart: unless-stopped
    networks:
      - localprom
    ports:
      - 9203:9203
    secrets:
      - sofom-dap-db-mgt-ro_uri
    entrypoint: sh -c "export DATA_SOURCE_NAME=$(cat /run/secrets/sofom-dap-db-mgt-ro_uri) && exec postgres_exporter --web.listen-address=:9203 --exclude-databases=template0,template1,rdsadmin" 
    links:
      - prometheus
  
secrets:
  sofom-dap-db-mgt-ro_uri:
    file: ./../secrets/sofom-dap-db-mgt-ro.conn