services:
  pgexp-calakmul-sofom-prod:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: pgexp-calakmul-sofom-prod
    restart: unless-stopped
    networks:
      - localprom
    ports:
      - 9193:9193
    secrets:
      - calakmul-sofom-prod_uri
    entrypoint: sh -c "export DATA_SOURCE_NAME=$(cat /run/secrets/calakmul-sofisofompo-prod_uri) && exec postgres_exporter --web.listen-address=:9193 --exclude-databases=template0,template1,rdsadmin" 
    links:
      - prometheus
  
secrets:
  calakmul-sofom-prod_uri:
    file: ./../secrets/calakmul-sofom-prod.conn