services:
  pgexp-credit-empowerment-db-mgt-ro:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: pgexp-credit-empowerment-db-mgt-ro
    restart: unless-stopped
    networks:
      - localprom
    ports:
      - 9201:9201
    secrets:
      - credit-empowerment-db-mgt-ro_uri
    entrypoint: sh -c "export DATA_SOURCE_NAME=$(cat /run/secrets/credit-empowerment-db-mgt-ro_uri) && exec postgres_exporter --web.listen-address=:9201 --exclude-databases=template0,template1,rdsadmin" 
    links:
      - prometheus
  
secrets:
  credit-empowerment-db-mgt-ro_uri:
    file: ./../secrets/credit-empowerment-db-mgt-ro.conn