services:
  pgexp-calakmul-sofipo-prod-ro:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: pgexp-calakmul-sofipo-prod-ro
    restart: unless-stopped
    networks:
      - localprom
    ports:
      - 9192:9192
    secrets:
      - calakmul-sofipo-prod-ro_uri
    entrypoint: sh -c "export DATA_SOURCE_NAME=$(cat /run/secrets/calakmul-sofipo-prod-ro_uri) && exec postgres_exporter --web.listen-address=:9192 --exclude-databases=template0,template1,rdsadmin" 
    links:
      - prometheus

secrets:
  calakmul-sofipo-prod-ro_uri:
    file: ./../secrets/calakmul-sofipo-prod-ro.conn