services:
  pgexp-apollo-db:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: pgexp-apollo-db
    restart: unless-stopped
    networks:
      - localprom
    ports:
      - 9198:9198
    secrets:
      - apollo-db_uri
    entrypoint: sh -c "export DATA_SOURCE_NAME=$(cat /run/secrets/apollo-db_uri) && exec postgres_exporter --web.listen-address=:9198 --exclude-databases=template0,template1,rdsadmin" 
    links:
      - prometheus
  
secrets:
  apollo-db_uri:
    file: ./../secrets/apollo-db.conn